name: Backend Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test_backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[backend]')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build .NET
        run: dotnet build --no-restore

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test .NET
        run: dotnet test --no-build --verbosity normal
