name: Build On Success

on:
  workflow_run:
    workflows: [.NET]
    types: [completed]

jobs:
  push_to_DockerHub:
    name: Push Images to DockerHub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Step into Backend working directory
        run: cd Backend

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goaldotnet:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/goaldotnet:latest
          run: |
            echo "Running the docker image"
            echo "Running tests"
