name: Frontend deploy on success

on:
  workflow_run:
    workflows: [Frontend Workflow]
    types: [completed]

jobs:
  push_to_DockerHub:
    name: Push Images to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/goaldotnet:goaldotnetfrontend ./frontend

      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/goaldotnet:goaldotnetfrontend

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/goaldotnetfrontend:latest
          run: |
            echo "Running the docker image"
            echo "Testing the Node.js app endpoints"
